"""empty message

Revision ID: fa6cb3f95843
Revises: bb017d0733ef
Create Date: 2021-11-12 16:35:09.948047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6cb3f95843'
down_revision = 'bb017d0733ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_file', sa.Column('user', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_file', 'user')
    # ### end Alembic commands ###
